version: "3.7"

services:
  redis:
    image: redis
    container_name: redis_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 7000:6379
  redis-queue:
    image: redis
    container_name: redis_queue
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379


  redis-commander:
    container_name: my-redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379,local:redis-queue:6379
    ports:
      - "8081:8081"
